FROM python:3.9
USER root
RUN apt-get update
RUN apt-get install -y vim
RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
RUN pip install django django-environ django-neomodel pytz